### ISSUE TITLE
1 - Variables

### ISSUE THREAD

**Issue by GerardoMR** [cetys-ice-imec/team-skype-ft-mariocas#2]
https://github.com/cetys-ice-imec/team-skype-ft-mariocas/blob/fd5ab15706528ff3678377a0cad3e63dc066296a/Lab/1.TemperatureControl/Temperature_Control.py#L15

Variable `Motor` is only used once, if you believe it add clarity for the next statement keep it, but rename it based PEP-8 naming conventions (using snake case). For example: `motor_pin`

**Comment by LuisS96** [comment]
I understand, yet it also says that any type variable name should normally use CapWords preferring short names and as you say it also recommends to use suffixes as the one you give for example. What do I do? Do I change it to `motor_pin` or to `Motor_pin`?
